(()=>{
  const SSID='Brennvika', PASSWORD='Halibut2026!';
  const QR='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASgAAAEoAQAAAADDfFG0AAABqklEQVR4nO2ZwYrDMAxE3yz9/1+eHiTbcViWHpZIBfvS1AxkGCRlJMl8cH4+AR3UQR3UQT2KegEono0sDMjyuu3LvkgvDKlaqBWCrduu7Kv0QuARZ7KcwqWSbdnXo4SsR9/4zShjkDO2+vDqg8p8HK5VgOXUbHrZruyr9FrBZDnq1/pAlvDqitK1Hxpm4nbdl32V/4oS7zRgut4V8WqNsrBthInaleE1crI1+xKUhDASWFn37Sj7/dk/h9LwpcJZtTTDyqOkdWVfVu9lLcWEuTyV8OqKWn4iC7zIQhZWLPTsyr4qHz1z0NE0ypco68u+6vsYVmKolZloTRvWmv2jqGVMR3g5EpEVeH3ZV84LZxJmeAnIuU5b9lWoSMh4SvMFgE79uh3NjjH7IJyzw/lbwqs7KuSyPQetAqSTj/vZ5xOX0pUxdvJxP9t+yKshQlcpu7Kv8vcpU/Tcs9/OTVEJr66obT8UNUyh0/ETv53X9m8Ooucm7fjVv1DOztsYKWdiDXj1QW37oRxGezdhJby6orb9UFoJjbmqznzifm6LoAfeeFAHdVAH9T+oNy/5t0/RRGe2AAAAAElFTkSuQmCC';
  const copy={en:{title:'Wi-Fi access',network:'Network',password:'Password',scan:'Scan to connect',note:'Scan the QR code with another phone, or enter the network name and password manually.',quick:'Brennvika · QR code below'},no:{title:'Wi-Fi-tilgang',network:'Nettverk',password:'Passord',scan:'Skann for å koble til',note:'Skann QR-koden med en annen mobil, eller skriv inn nettverksnavn og passord manuelt.',quick:'Brennvika · QR-kode nedenfor'},de:{title:'WLAN-Zugang',network:'Netzwerk',password:'Passwort',scan:'Zum Verbinden scannen',note:'Scannen Sie den QR-Code mit einem anderen Handy oder geben Sie Netzwerkname und Passwort manuell ein.',quick:'Brennvika · QR-Code unten'}};
  const style=document.createElement('style');
  style.textContent='.wifi-live{display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:24px;align-items:center}.wifi-credentials{display:grid;gap:12px;margin:18px 0}.wifi-credential small{display:block;color:var(--muted)}.wifi-credential strong{font-size:20px;overflow-wrap:anywhere}.wifi-qr{text-align:center}.wifi-qr img{display:block;width:210px;height:210px;max-width:100%;margin:auto;background:white}@media(max-width:650px){.wifi-live{grid-template-columns:1fr}}';document.head.appendChild(style);
  function render(){
    const code=document.documentElement.lang,language=code==='nb'?'no':code==='de'?'de':'en',c=copy[language];
    const quick=[...document.querySelectorAll('#quickGrid .quick-item')].find(x=>(x.querySelector('small')?.textContent||'').replace(/[^A-Za-z]/g,'')==='WiFi');
    const quickText=quick?.querySelector('strong');if(quickText&&quickText.textContent!==c.quick)quickText.textContent=c.quick;
    const wifi=document.getElementById('wifi'),card=wifi?.querySelector('.card.wide.blue')||wifi?.querySelector('.card.wide');
    if(!card||card.dataset.wifiRendered===language)return;
    card.dataset.wifiRendered=language;
    card.innerHTML=`<div class="wifi-live"><div><h3>${c.title}</h3><div class="wifi-credentials"><div class="wifi-credential"><small>${c.network}</small><strong>${SSID}</strong></div><div class="wifi-credential"><small>${c.password}</small><strong>${PASSWORD}</strong></div></div><p>${c.note}</p></div><div class="wifi-qr"><img src="${QR}" width="296" height="296" alt="${c.scan}"><small>${c.scan}</small></div></div>`;
  }
  const content=document.getElementById('content');if(content)new MutationObserver(render).observe(content,{childList:true,subtree:true});render();
})();