"""Generate the Norwegian and English static website from verified source assets."""
from pathlib import Path
import html, json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist'
PHOTOS = json.loads((ROOT / 'source/gallery.json').read_text())
ROLES = json.loads((ROOT / 'source/visuals.json').read_text())
BOOKING = json.loads((ROOT / 'source/booking.json').read_text())
GUIDE = 'https://zgvhnbgggk-code.github.io/brennvika-panorama/'
MAP = 'https://www.google.com/maps/search/?api=1&query=Brennvikveien+37%2C+8294+Hamar%C3%B8y%2C+Norway'
APPLE = 'https://maps.apple.com/?q=Brennvikveien%2037%2C%208294%20Hamar%C3%B8y%2C%20Norway'
CHECKOUT = BOOKING['checkout']
ROUTES = {
 'no': {'home':'/', 'cabin':'/hytta/', 'gallery':'/galleri/', 'explore':'/opplevelser/', 'location':'/beliggenhet/', 'booking':'/bestill/', 'privacy':'/personvern/'},
 'en': {'home':'/en/', 'cabin':'/en/cabin/', 'gallery':'/en/gallery/', 'explore':'/en/experiences/', 'location':'/en/location/', 'booking':'/en/book/', 'privacy':'/en/privacy/'}
}
LABELS = {
 'no': {'home':'Hjem','cabin':'Hytta','gallery':'Bilder','explore':'Opplevelser','location':'Beliggenhet','booking':'Se ledige datoer','privacy':'Personvern'},
 'en': {'home':'Home','cabin':'The cabin','gallery':'Gallery','explore':'Experiences','location':'Location','booking':'Check availability','privacy':'Privacy'}
}
def t(lang, no, en): return no if lang == 'no' else en
def esc(s): return html.escape(str(s), quote=True)
def url(lang, key): return ROUTES[lang][key]
def caption(p, lang): return p['caption_'+lang]
def pic(lang, role, cls='', eager=False):
 p=PHOTOS[ROLES[role]] if isinstance(role,str) else PHOTOS[role]
 variants={p['small_width']:p['small'],p['image_width']:p['image'],p['large_width']:p['large']}
 srcset=', '.join(f'{file} {width}w' for width,file in sorted(variants.items()))
 sizes='100vw' if cls=='hero-image' or role=='closing' else '(max-width:700px) 50vw, 33vw' if isinstance(role,int) else '(max-width:700px) 100vw, 65vw'
 return f'<img class="{cls}" src="{p["image"]}" srcset="{srcset}" sizes="{sizes}" alt="{esc(caption(p,lang))}" width="{p["width"]}" height="{p["height"]}" loading="{"eager" if eager else "lazy"}" decoding="async"{chr(32)+"fetchpriority=high" if eager else ""}>'
def button(lang, key, label=None, style='', arrow=True):
 return f'<a class="button {style}" href="{url(lang,key)}">{label or LABELS[lang][key]}{ "<span class=arr aria-hidden=true>↗</span>" if arrow else ""}</a>'
def link(lang, key, label=None):
 return f'<a class="text-link" href="{url(lang,key)}">{label or LABELS[lang][key]} <span aria-hidden="true">↗</span></a>'
def eyebrow(text): return f'<p class="eyebrow">{text}</p>'
def head(lang,key,title,intro):
 return f'<section class="page-head"><div class="wrap">{eyebrow("Brennvik Panorama · "+LABELS[lang][key])}<h1>{title}</h1><p class="intro">{intro}</p></div></section>'
def section_head(lang,ey,title,text,more=''):
 return f'<div class="section-head"><div>{eyebrow(ey)}<h2>{title}</h2></div><div class="intro"><p>{text}</p>{more}</div></div>'
def faq(q,a): return f'<details class="faq"><summary>{q}</summary><div class="answer">{a}</div></details>'
def photo_link(lang,i,cls=''):
 p=PHOTOS[i]
 return f'<a class="{cls}" href="{p["full"]}" data-photo="{i}" aria-label="{esc(t(lang,"Åpne bilde: ","Open photo: ")+caption(p,lang))}">{pic(lang,i)}</a>'
def closing(lang):
 return f'''<section class="closing">{pic(lang,'closing')}<div class="wrap">{eyebrow(t(lang,'Et lite sted ved det store havet','A little place beside the open sea'))}<h2>{t(lang,'Noen dager fortjener<br>en annen utsikt.','Some days deserve<br>a different view.')}</h2><p>{t(lang,'Finn dagene som passer for deg. Vi gleder oss til å ønske deg velkommen til Brennvik Panorama.','Find the dates that work for you. We look forward to welcoming you to Brennvik Panorama.')}</p>{button(lang,'booking',style='light')}</div></section>'''
def layout(lang,key,content,title,desc,lightbox=False):
 labels=LABELS[lang]
 nav=''.join(f'<a href="{url(lang,k)}"'+(' aria-current="page"' if key==k else '')+f'>{labels[k]}</a>' for k in ['cabin','gallery','explore','location'])
 langs=''.join(f'<a href="{url(l,key)}" lang="{l}" hreflang="{"nb" if l=="no" else "en"}"'+(' aria-current="page"' if l==lang else '')+f'>{l.upper()}</a>'+('<span aria-hidden="true">/</span>' if l=='no' else '') for l in ['no','en'])
 footnav=''.join(f'<li><a href="{url(lang,k)}">{labels[k]}</a></li>' for k in ['cabin','gallery','explore','location','booking'])
 guide=GUIDE+('no.html' if lang=='no' else 'index.html')
 lb=''
 if lightbox:
  data=[{'full':p['full'],'caption':caption(p,lang)} for p in PHOTOS]
  lb=f'''<script type="application/json" id="gallery-data">{json.dumps(data,ensure_ascii=False).replace('<','\\u003c')}</script><dialog class="lightbox" id="lightbox" aria-label="{t(lang,'Bildegalleri','Photo gallery')}"><div class="lightbox-inner"><div class="lightbox-top"><span class="lightbox-count" aria-live="polite"></span><button class="lightbox-close" aria-label="{t(lang,'Lukk bildegalleriet','Close gallery')}" type="button">×</button></div><div class="lightbox-stage"><img class="lightbox-img" alt=""><button type="button" class="lightbox-prev" aria-label="{t(lang,'Forrige bilde','Previous photo')}">‹</button><button type="button" class="lightbox-next" aria-label="{t(lang,'Neste bilde','Next photo')}">›</button></div><p class="lightbox-caption" aria-live="polite"></p></div></dialog>'''
 favicon="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2312343c'/%3E%3Ctext x='32' y='44' text-anchor='middle' font-family='Georgia,serif' font-size='38' fill='%23f6f2e9'%3EB%3C/text%3E%3C/svg%3E"
 htmltxt=f'''<!doctype html>
<html lang="{t(lang,'nb','en')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f6f2e9"><meta name="robots" content="noindex,nofollow"><title>{esc(title)} · Brennvik Panorama</title><meta name="description" content="{esc(desc)}"><link rel="icon" type="image/svg+xml" href="{favicon}"><link rel="stylesheet" href="/site.css"><script defer src="/site.js"></script></head>
<body class="{key}-page"><a class="skip" href="#main">{t(lang,'Gå til innhold','Skip to content')}</a><header class="header"><div class="header-inner wrap"><a class="brand" href="{url(lang,'home')}" aria-label="Brennvik Panorama · {labels['home']}"><span class="brand-title">Brennvik Panorama</span><span class="brand-sub">Hamarøy · {t(lang,'Nord-Norge','Northern Norway')}</span></a><nav id="site-nav" class="nav" aria-label="{t(lang,'Hovedmeny','Main navigation')}">{nav}</nav><div class="language" aria-label="{t(lang,'Språk','Language')}">{langs}</div>{button(lang,'booking',arrow=False)}<button class="menu-toggle" aria-controls="site-nav" aria-expanded="false" type="button">{t(lang,'Meny','Menu')} ☰</button></div></header><main id="main">{content}</main>
<footer class="footer"><div class="wrap"><div class="footer-grid"><div><h2>Brennvik Panorama</h2><p>Brennvikveien 37<br>8294 Hamarøy · {t(lang,'Norge','Norway')}</p><img class="footer-logo" src="/assets/logo.webp" width="360" height="120" loading="lazy" alt="Skoglund Heim AS"></div><div><h3>{t(lang,'Utforsk','Explore')}</h3><ul>{footnav}</ul></div><div><h3>{t(lang,'Eva &amp; Dan','Eva &amp; Dan')}</h3><p><a href="tel:+4795403024">Eva · +47 954 03 024</a><br><a href="tel:+4791541662">Dan · +47 915 41 662</a></p><p style="margin-top:22px"><a href="{guide}" target="_blank" rel="noopener">{t(lang,'Åpne gjesteguiden','Open the guest guide')} ↗</a></p><p style="margin-top:14px"><a href="{url(lang,'privacy')}">{labels['privacy']}</a></p></div></div><div class="footer-bottom"><span>© 2026 Skoglund Heim AS · Brennvik Panorama</span><span>{t(lang,'Et sted å lande. En utsikt å ta med hjem.','A place to slow down. A view to take home.')}</span></div></div></footer>
<div class="mobile-book"><span>{t(lang,'Din pause ved havet','Your stay by the sea')}</span>{button(lang,'booking',arrow=False)}</div>{lb}</body></html>'''
 target=OUT/url(lang,key).strip('/')/'index.html'
 target.parent.mkdir(parents=True,exist_ok=True);target.write_text(htmltxt)

def home(lang):
 hero=f'''<section class="hero">{pic(lang,'hero','hero-image',True)}<div class="hero-content wrap">{eyebrow(t(lang,'Hamarøy · Vestfjorden · Nord-Norge','Hamarøy · Vestfjorden · Northern Norway'))}<h1>{t(lang,'Tettere på havet.<br><em>Lenger fra hverdagen.</em>','Closer to the sea.<br><em>Further from everyday.</em>')}</h1><p class="hero-lead">{t(lang,'Et lite hus, et stort hav og tid til å være til stede. Velkommen til Brennvik Panorama.','A little cabin, an open sea and time to simply be. Welcome to Brennvik Panorama.')}</p><div class="hero-actions">{button(lang,'booking',style='light')}{button(lang,'cabin',t(lang,'Se hytta','Explore the cabin'),style='line',arrow=False)}</div></div><div class="hero-bottom">{t(lang,'Brennvikveien 37 · Et eget sted ved Vestfjorden','Brennvikveien 37 · A place of your own by Vestfjorden')}</div></section>'''
 facts=f'''<div class="wrap facts"><div class="fact"><strong>49 m²</strong><span>{t(lang,'Hele hytta for dere selv','The whole cabin to yourselves')}</span></div><div class="fact"><strong>2 {t(lang,'soverom','bedrooms')}</strong><span>{t(lang,'Plass til å finne roen','Room to settle in')}</span></div><div class="fact"><strong>{t(lang,'Ved sjøen','By the sea')}</strong><span>{t(lang,'Med utsikt over Vestfjorden','Views across Vestfjorden')}</span></div><div class="fact"><strong>{t(lang,'4 gjester','4 guests')}</strong><span>{t(lang,'To dobbeltsenger','Two double beds')}</span></div></div>'''
 intro=section_head(lang,t(lang,'Et sted å lande','A place to slow down'),t(lang,'Utsikten er stor.<br>Resten er enkelt.','A wide-open view.<br>A simpler kind of day.'),t(lang,'Start dagen med kaffe og havet utenfor vinduet. Lag middag sammen, finn en plass på terrassen og se lyset skifte over fjorden. Her trenger ikke dagene å være fulle for å være fine.','Start with coffee and the sea outside your window. Cook together, find a seat on the terrace and watch the light move across the fjord. The best days here leave a little space.'),link(lang,'cabin',t(lang,'Bli kjent med hytta','Get to know the cabin')))
 pairs=f'''<div class="photo-pair"><figure>{pic(lang,'living')}<figcaption>{t(lang,'Ro inne. Havet rett utenfor.','Comfort inside. The sea just outside.')}</figcaption></figure><figure>{pic(lang,'terrace')}<figcaption>{t(lang,'En plass i frisk luft, i ditt eget tempo.','Fresh air and a moment of your own.')}</figcaption></figure></div>'''
 features=[(t(lang,'En hytte helt for dere','A cabin of your own'),t(lang,'To soverom, stue og kjøkken, bad og terrasse. Dere har hele hytta for dere selv.','Two bedrooms, a living area and kitchen, bathroom and terrace. The entire cabin is yours.')),(t(lang,'Behagelig å komme hjem til','Comfort to come back to'),t(lang,'Gulvvarme, varmepumpe og Wi-Fi gjør det lett å finne seg til rette etter en dag ute.','Underfloor heating, a heat pump and Wi-Fi make it easy to settle in after a day outdoors.')),(t(lang,'Nær det dere kom for','Close to what brought you here'),t(lang,'Ta dagen som den kommer, med kysten, Tranøy og Hamarøys natur som utgangspunkt.','Let the day unfold, with the coast, Tranøy and the landscapes of Hamarøy to explore.'))]
 feature='<div class="feature-row">'+''.join(f'<div><h3>{a}</h3><p>{b}</p></div>' for a,b in features)+'</div>'
 story=f'''<section class="section sea-section"><div class="wrap story-split"><div>{eyebrow(t(lang,'Hamarøy, i ditt tempo','Hamarøy, at your own pace'))}<h2>{t(lang,'En liten avstikker.<br>Et stort minne.','A little detour.<br>A lasting memory.')}</h2><p>{t(lang,'En tur til Tranøy. Salt luft på kaia. En stille ettermiddag langs kysten. Brennvik Panorama er et godt utgangspunkt for å oppleve Hamarøy – eller for å bli akkurat der du er.','A visit to Tranøy. Salt air at the quay. A quiet afternoon along the coast. Brennvik Panorama is a base for exploring Hamarøy — and for days when you would rather stay right here.')}</p><p>{t(lang,'Gjesteguiden vår samler utflukter og praktiske råd, slik at det blir lett å finne dine egne favoritter.','Our guest guide brings together local outings and practical advice to help you find your own favourites.')}</p>{button(lang,'explore',t(lang,'Opplev Hamarøy','Explore Hamarøy'),style='light')}</div>{pic(lang,'experience')}</div></section>'''
 strip='<div class="photo-strip">'+''.join(photo_link(lang,ROLES[r]) for r in ['exterior','kitchen','view'])+'</div>'
 gallery=f'''<section class="section"><div class="wrap">{section_head(lang,t(lang,'Bilder fra Brennvik Panorama','Photographs from Brennvik Panorama'),t(lang,'Ta en titt.<br>Se for deg dagene.','Take a look.<br>Picture your days here.'),t(lang,'Se hytta, rommene og omgivelsene i bildegalleriet.','Explore the cabin, its rooms and the surroundings in our photo gallery.'))}{strip}<div class="strip-bottom"><p>{t(lang,'Ekte bilder fra hytta og området.','Real photographs of the cabin and the area.')}</p>{link(lang,'gallery',t(lang,'Se alle bildene','View all photos'))}</div></div></section>'''
 layout(lang,'home',hero+facts+f'<section class="section"><div class="wrap">{intro}{pairs}{feature}</div></section>'+story+gallery+closing(lang),t(lang,'En hytte ved Vestfjorden i Hamarøy','A cabin by Vestfjorden in Hamarøy'),t(lang,'Opplev Brennvik Panorama: en moderne hytte ved sjøen i Hamarøy. Se bilder, bli kjent med området og finn ledige datoer.','Discover Brennvik Panorama, a modern seaside cabin in Hamarøy, Northern Norway. Explore the photos and find available dates.'),True)

def cabin(lang):
 content=head(lang,'cabin',t(lang,'Liten hytte.<br>God plass til å senke skuldrene.','A little cabin.<br>Room to unwind.'),t(lang,'49 m² med to soverom, stue og kjøkken, bad og terrasse. En oversiktlig hytte på ett plan, med hele stedet for dere selv.','49 m² with two bedrooms, a living area and kitchen, bathroom and terrace. A single-level cabin, all to yourselves.'))
 content+=f'<div class="wrap wide-photo"><figure>{pic(lang,"exterior",eager=True)}<figcaption>{t(lang,"Brennvik Panorama, ved Vestfjorden i Hamarøy.","Brennvik Panorama, beside Vestfjorden in Hamarøy.")}</figcaption></figure></div>'
 rooms=[('living',t(lang,'Stue & kjøkken','Living & kitchen'),t(lang,'Her er utsikten en del av rommet.','The view is part of the room.'),t(lang,'Stue og kjøkken henger sammen i et åpent rom. Her kan dere lage mat, spise sammen og ta en rolig kveld med havet som bakgrunn. Kjøkkenet har koketopp, stekeovn, kjøleskap og oppvaskmaskin.','The living area and kitchen share an open space. Cook, eat together and enjoy a quiet evening with the sea as your backdrop. The kitchen has a hob, oven, refrigerator and dishwasher.')),('bedroom',t(lang,'To soverom','Two bedrooms'),t(lang,'En rolig slutt på dagen.','A quiet end to the day.'),t(lang,'To separate soverom med dobbeltseng gir plass til opptil fire gjester. Hytta har en kompakt planløsning med fellesarealene like ved.','Two separate bedrooms with double beds accommodate up to four guests. The cabin has a compact layout with the shared living space close by.')),('bathroom',t(lang,'Bad & komfort','Bathroom & comfort'),t(lang,'Det praktiske er på plass.','The everyday essentials.'),t(lang,'Bad med dusj og en kompakt vaskemaskin. Gulvvarme og varmepumpe gir behagelig temperatur, og dere kan justere varmen under oppholdet.','A bathroom with shower and a compact washing machine. Underfloor heating and a heat pump keep the cabin comfortable, and you can adjust the temperature during your stay.')),('terrace',t(lang,'Terrassen','The terrace'),t(lang,'Ta dagen med ut.','Take your day outside.'),t(lang,'Sett deg ned med noe varmt i koppen og la utsikten få tid. Terrassen er en del av hyttelivet når været spiller på lag.','Take a warm drink outside and give the view a little time. The terrace is part of cabin life whenever the weather allows.'))]
 content+='<section class="section-small"><div class="wrap">'+''.join(f'<article class="room-row"><div class="room-photo">{pic(lang,r)}</div><div class="room-copy">{eyebrow(e)}<h2>{h}</h2><p>{p}</p></div></article>' for r,e,h,p in rooms)+'</div></section>'
 am=t(lang,['To soverom','Kjøkken med oppvaskmaskin','Bad med dusj','Kompakt vaskemaskin','Wi-Fi','Varmepumpe','Gulvvarme','Terrasse','Parkering ved hytta'],['Two bedrooms','Kitchen with dishwasher','Bathroom with shower','Compact washing machine','Wi-Fi','Heat pump','Underfloor heating','Terrace','Parking beside the cabin'])
 content+=f'<section class="section-small"><div class="wrap">{eyebrow(t(lang,"Fasiliteter","Amenities"))}<h2 class="serif" style="font-size:40px">{t(lang,"Det dere trenger for noen gode dager.","The essentials for a comfortable stay.")}</h2><ul class="amenities">'+''.join(f'<li>{a}</li>' for a in am)+'</ul></div></section>'
 faqhtml=faq(t(lang,'Når kan vi sjekke inn og ut?','What are the check-in and checkout times?'),t(lang,'Innsjekk fra kl. 15.00 og utsjekk innen kl. 11.00, med mindre dere har avtalt noe annet. Se bestillingsbekreftelsen for tidene som gjelder deres opphold.','Check-in is from 15:00 and checkout is by 11:00, unless otherwise agreed. Your booking confirmation contains the times for your stay.'))
 faqhtml+=faq(t(lang,'Kan vi drikke vannet fra springen?','Can we drink the tap water?'),t(lang,'Hytta har vann fra en privat fjellkilde. <strong>Ikke drikk vann direkte fra springen.</strong> På kjøkkenet står en Waterdrop A2G vannrenser. Vi kan ikke garantere vannkvaliteten etter rensing; kjøpt drikkevann anbefales for størst mulig trygghet. Gjesteguiden forklarer bruken og hvor dere kan hente kommunalt drikkevann.','The cabin has water from a private mountain source. <strong>Do not drink water directly from the taps.</strong> A Waterdrop A2G purifier is provided in the kitchen. We cannot guarantee the quality of the filtered water; bottled drinking water is recommended for the greatest certainty. The guest guide explains how to use the purifier and where to collect municipal drinking water.'))
 faqhtml+=faq(t(lang,'Hvordan får vi adgang til hytta?','How do we get into the cabin?'),t(lang,'Dere får innsjekkinformasjon og personlig dørkode i forbindelse med oppholdet. Les gjesteguiden før ankomst, og ta kontakt med oss hvis noe er uklart.','You will receive arrival information and a personal door code for your stay. Read the guest guide before arriving and contact us if anything is unclear.'))
 faqhtml+=faq(t(lang,'Hva er inkludert, og hvilke vilkår gjelder?','What is included, and which terms apply?'),t(lang,'Pris, eventuelle tillegg, gjesteantall og avbestillingsvilkår vises i Lodgify før du bekrefter bestillingen. Sjekk disse opplysningene for datoene du ønsker.','The price, any additional charges, guest limit and cancellation terms are shown in Lodgify before you confirm. Check these details for your chosen dates.'))
 content+=f'<section class="section"><div class="wrap practical"><div>{eyebrow(t(lang,"Før du bestiller","Before you book"))}<h2 class="serif" style="font-size:42px;line-height:1.15">{t(lang,"Fint å vite<br>før dere kommer.","A few things to know<br>before you arrive.")}</h2></div><div>{faqhtml}</div></div></section>'+closing(lang)
 layout(lang,'cabin',content,t(lang,'Hytta og fasilitetene','The cabin and amenities'),t(lang,'Bli kjent med hytta: to soverom, kjøkken, bad, terrasse og praktisk informasjon før du bestiller.','Explore the cabin: two bedrooms, kitchen, bathroom, terrace and practical information before booking.'))

def gallery(lang):
 content=head(lang,'gallery',t(lang,'Et lite innblikk.<br>En stor utsikt.','A closer look.<br>A wider view.'),t(lang,'Bilder fra hytta, rommene og omgivelsene. Åpne et bilde for å se det større, og bla deg videre i galleriet.','Photographs of the cabin, its rooms and surroundings. Open a photo for a larger view and browse through the gallery.'))
 categories=[('all',t(lang,'Alle bilder','All photos')),('cabin',t(lang,'Hytta','The cabin')),('outside',t(lang,'Ute & utsikt','Outside & views'))]
 filters=''.join(f'<button type="button" data-filter="{k}" aria-pressed="{"true" if k=="all" else "false"}">{v}</button>' for k,v in categories)
 grid=''
 for i,p in enumerate(PHOTOS):
  grid+=f'<a class="gallery-card" href="{p["full"]}" data-photo="{i}" data-category="{p["category"]}" aria-label="{esc(t(lang,"Åpne: ","Open: ")+caption(p,lang))}"><figure>{pic(lang,i,eager=i<3)}<figcaption>{esc(caption(p,lang))}</figcaption></figure></a>'
 content+=f'<section class="section-small" style="padding-top:0"><div class="wrap"><div class="gallery-toolbar"><div class="filters" role="group" aria-label="{t(lang,"Filtrer bilder","Filter photos")}">{filters}</div><p id="gallery-count" data-noun="{t(lang,"bilder","photos")}" aria-live="polite">{len(PHOTOS)} {t(lang,"bilder","photos")}</p></div><div class="gallery-grid">{grid}</div></div></section>'+closing(lang)
 layout(lang,'gallery',content,t(lang,'Bildegalleri','Photo gallery'),t(lang,'Se hele bildegalleriet fra Brennvik Panorama. Ekte bilder av hytta, rommene, terrassen og utsikten.','View the full Brennvik Panorama gallery. Genuine photographs of the cabin, rooms, terrace and views.'),True)

def explore(lang):
 content=head(lang,'explore',t(lang,'Finn ditt<br>Hamarøy.','Find your kind<br>of Hamarøy.'),t(lang,'Litt kystliv. En avstikker til Tranøy. En dag med utsikt. Velg etter været, nysgjerrigheten og hvor god tid du har.','A little coastal life. A detour to Tranøy. A day with a view. Follow the weather, your curiosity and your own pace.'))
 experiences=[
 ('experience',t(lang,'Kystliv','Coastal life'),t(lang,'Små øyeblikk<br>langs havet.','Small moments<br>by the sea.'),t(lang,'Ta en rusletur, finn en lun plass og la dagen gå litt saktere. Landskapet rundt Hamarøy gir mange grunner til å stoppe. Ta med et ekstra lag klær, også på fine sommerdager.','Take a walk, find a sheltered spot and let the day slow down. The Hamarøy coastline gives you plenty of reasons to stop. Bring an extra layer, even on a sunny summer day.'),'', ''),
 ('view',t(lang,'Tranøy','Tranøy'),t(lang,'Kysthus, kunst<br>og et fyr i havgapet.','Coastal houses, art<br>and a lighthouse.'),t(lang,'Gå på oppdagelse blant husene og kunsten på Tranøy, og legg turen mot Tranøy fyr når forholdene passer. Sjekk åpningstider før du planlegger et måltid eller et besøk inne.','Explore the houses and outdoor art on Tranøy, then head towards Tranøy lighthouse when conditions allow. Check opening hours before planning a meal or a visit inside.'),'https://tranoyfyr.no/',t(lang,'Besøk Tranøy fyr','Visit Tranøy lighthouse')),
 ('sea',t(lang,'En dag ute','A day outdoors'),t(lang,'Følg kysten.<br>Eller ta veien mot fjellet.','Follow the coast.<br>Or head for the hills.'),t(lang,'Hamarøy har muligheter for både rolige turer og lengre utflukter. I gjesteguiden finner dere blant annet Glimma, Skaftheia og Hamarøyskaftet. Selve toppen av Hamarøyskaftet krever teknisk klatring og egnet kompetanse.','Hamarøy offers gentle walks and longer outings. Our guest guide includes Glimma, Skaftheia and Hamarøyskaftet. The summit of Hamarøyskaftet requires technical climbing and appropriate expertise.'),GUIDE+('no.html#explore' if lang=='no' else 'index.html#explore'),t(lang,'Finn turforslag i guiden','Find outings in the guide')),
 ('closing',t(lang,'Lys & årstider','Light & seasons'),t(lang,'Se hvordan<br>lyset forandrer alt.','See how the light<br>changes everything.'),t(lang,'Lyse sommernetter og mørke vinterkvelder gir to helt forskjellige opphold. På klare, mørke kvelder kan nordlyset vise seg. Det er aldri en garanti, men det finnes god grunn til å se opp.','Light summer nights and dark winter evenings make for very different stays. On clear, dark nights, the northern lights may appear. There is never a guarantee, but there is every reason to look up.'),'','')]
 content+='<section class="section-small"><div class="wrap experience-list">'
 for r,e,h,p,u,l in experiences:
  image=pic(lang,r)
  image_note=t(lang,'Foto fra hytta og nærområdet.','Photograph from the cabin and surrounding area.')
  if r=='view':
   image=f'<img src="/assets/experiences/tranoy-lighthouse.webp" alt="{t(lang,"Tranøy fyr ved Vestfjorden","Tranøy lighthouse by Vestfjorden")}" width="960" height="640" loading="lazy" decoding="async">'
   image_note='Karin Beate Nøsterud / Nordic Co-operation · <a href="https://commons.wikimedia.org/wiki/File:Hamaroy_fyr,_Norge_(1).jpg" target="_blank" rel="noopener">CC BY 2.5 DK</a>'
  elif r=='sea':
   image=f'<img src="/assets/experiences/hamaroyskaftet.webp" alt="{t(lang,"Fjellet Hamarøyskaftet","The mountain Hamarøyskaftet")}" width="960" height="640" loading="lazy" decoding="async">'
   image_note='TorbjørnS · <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener">CC0</a>'
  content+=f'<article class="experience"><figure class="experience-image">{image}<figcaption class="photo-credit">{image_note}</figcaption></figure><div>{eyebrow(e)}<h2>{h}</h2><p>{p}</p>'+ (f'<a class="text-link" href="{esc(u)}" target="_blank" rel="noopener">{l} ↗</a>' if u else '')+'</div></article>'
 content+='</div></section>'
 content+=f'<section class="section"><div class="wrap practical"><div>{eyebrow(t(lang,"Vår gjesteguide","Our guest guide"))}<h2 class="serif" style="font-size:42px;line-height:1.15">{t(lang,"Flere ideer.<br>Færre ting å lure på.","More ideas.<br>Less to figure out.")}</h2></div><div><p>{t(lang,"Gjesteguiden samler lokale opplevelser, fisketurer, kunst, dagligvarer og alt det praktiske ved oppholdet. Den er laget for å være nyttig både før dere kommer og mens dere er her.","Our guest guide brings together local experiences, fishing outings, art, groceries and the practical details of your stay. It is useful both before you arrive and while you are here.")}</p><a class="button" style="margin-top:25px" href="{GUIDE+("no.html" if lang=="no" else "index.html")}" target="_blank" rel="noopener">{t(lang,"Åpne gjesteguiden","Open the guest guide")} ↗</a></div></div></section>'+closing(lang)
 layout(lang,'explore',content,t(lang,'Opplevelser i Hamarøy','Experiences in Hamarøy'),t(lang,'Opplev kysten, Tranøy, fjellene og lyset i Hamarøy. Finn inspirasjon til oppholdet ved Brennvik Panorama.','Explore the coast, Tranøy, mountains and changing light of Hamarøy. Find inspiration for your stay at Brennvik Panorama.'))

def location(lang):
 content=head(lang,'location',t(lang,'Veien hit er starten<br>på noe roligere.','The way here is the start<br>of something quieter.'),t(lang,'Du finner Brennvik Panorama ved Vestfjorden i Hamarøy, med Tranøy og kystlandskapet like i nærheten.','Find Brennvik Panorama beside Vestfjorden in Hamarøy, close to Tranøy and the coastal landscape.'))
 content+=f'''<section class="section-small"><div class="wrap location-grid"><div>{eyebrow(t(lang,'Finn frem','Find us'))}<h2>Brennvik Panorama</h2><p>{t(lang,'Bruk hele adressen når du planlegger reisen. Kartlenkene åpner plasseringen i kartappen din.','Use the full address when planning your journey. The links open the location in your map app.')}</p><div class="address">Brennvikveien 37<br>8294 Hamarøy<br>{t(lang,'Norge','Norway')}</div><div class="map-actions"><a class="button" href="{esc(MAP)}" target="_blank" rel="noopener">Google Maps ↗</a><a class="button line" href="{esc(APPLE)}" target="_blank" rel="noopener">Apple Maps ↗</a></div></div><div class="map-panel">{pic(lang,'location',eager=True)}<div class="map-caption"><span>Hamarøy · Nordland</span><a href="{esc(MAP)}" target="_blank" rel="noopener">{t(lang,'Se på kart','View on map')} ↗</a></div></div></div></section>'''
 qas=faq(t(lang,'Den siste delen av kjøreturen','The last part of the drive'),t(lang,'Ta av hovedveien og inn på Brennvikveien. Hold lav fart, maksimalt 30 km/t på den siste strekningen. Ta til høyre ved krysset ved transformatorstasjonen og følg veien ned mot sjøen. Hytta ligger på høyre side.','Turn off the main road onto Brennvikveien. Drive slowly, at no more than 30 km/h on the final stretch. Turn right at the junction by the electrical transformer station and continue downhill towards the sea. The cabin is on your right.'))
 qas+=faq(t(lang,'Parkering','Parking'),t(lang,'Parker ved hytta, uten å blokkere veien eller tilkomsten for andre kjøretøy.','Park beside the cabin without blocking the road or access for other vehicles.'))
 qas+=faq(t(lang,'Planlegg reisen etter årstiden','Plan for the season'),t(lang,'Sjekk vær, føre og eventuelle ferger før avreise. Sett av tid til stopp underveis. På vinteren må bilen være utstyrt for vinterføre.','Check weather, road conditions and any ferry connections before you travel. Leave time for stops along the way. In winter, your car must be equipped for winter driving.'))
 content+=f'''<section class="section"><div class="wrap practical"><div>{eyebrow(t(lang,'Før ankomst','Before arrival'))}<h2 class="serif" style="font-size:42px;line-height:1.15">{t(lang,'Den siste biten<br>ned til havet.','The last stretch<br>down to the sea.')}</h2></div><div>{qas}</div></div></section>'''
 content+=f'''<section class="section-small" style="background:var(--paper2)"><div class="wrap practical"><div>{eyebrow(t(lang,'Spør oss','Get in touch'))}<h2 class="serif" style="font-size:42px;line-height:1.15">{t(lang,'Vi hjelper deg<br>gjerne på vei.','We are happy<br>to help you plan.')}</h2></div><div><p>{t(lang,'Lurer du på noe før bestilling eller ankomst? Ta kontakt med Eva eller Dan. Har du allerede bestilt, kan du også svare oss i bestillingskanalen.','Have a question before booking or arriving? Contact Eva or Dan. If you have already booked, you can also reply through your booking channel.')}</p><div class="contact-block"><div><small>Eva</small><a href="tel:+4795403024">+47 954 03 024</a></div><div><small>Dan</small><a href="tel:+4791541662">+47 915 41 662</a></div></div></div></div></section>'''+closing(lang)
 layout(lang,'location',content,t(lang,'Beliggenhet og kontakt','Location and contact'),t(lang,'Finn veien til Brennvik Panorama, Brennvikveien 37 i Hamarøy. Kart, veibeskrivelse og kontakt med vertene.','Find Brennvik Panorama at Brennvikveien 37 in Hamarøy. Maps, directions and contact details for your hosts.'))

def booking(lang):
 content=head(lang,'booking',t(lang,'Finn noen dager<br>som er bare deres.','Find a few days<br>to call your own.'),t(lang,'Velg datoer og antall gjester for å se tilgjengelighet og pris. Bestillingen fullføres på engelsk hos Lodgify.','Choose your dates and number of guests to see availability and pricing. Your booking is handled by Lodgify.'))
 widget=BOOKING.get('embed_'+lang,'')
 if not widget: raise ValueError('A verified booking embed is required before generating the site')
 content+=f'''<section class="section-small" style="padding-top:0"><div class="wrap booking-layout"><aside class="booking-info">{pic(lang,'exterior',eager=True)}<h2>Brennvik Panorama</h2><p>Hamarøy · {t(lang,'Nord-Norge','Northern Norway')}</p><ul><li>{t(lang,'Hele hytta · 49 m²','Entire cabin · 49 m²')}</li><li>{t(lang,'To soverom','Two bedrooms')}</li><li>{t(lang,'Innsjekk fra kl. 15.00','Check-in from 15:00')}</li><li>{t(lang,'Utsjekk innen kl. 11.00','Checkout by 11:00')}</li></ul><p>{t(lang,'Du ser gjeldende pris, tillegg og vilkår før du bekrefter.','You will see the current price, any extras and the terms before you confirm.')}</p>{link(lang,'cabin',t(lang,'Les om hytta og drikkevannet','Read about the cabin and drinking water'))}</aside><div><div class="booking-panel"><h2>{t(lang,'Ditt opphold','Your stay')}</h2><p>{t(lang,'Velg datoene du ønsker.','Select your preferred dates.')}</p><div class="booking-embed">{widget}</div><div class="booking-direct"><a class="text-link" href="{esc(CHECKOUT)}" target="_blank" rel="noopener">{t(lang,'Åpne bestillingen i eget vindu','Open booking in a new window')} ↗</a></div></div><p class="booking-help">{t(lang,'Hvis bestillingsfeltet ikke vises, åpne bestillingen i eget vindu. Har du spørsmål, ring','If the booking form does not appear, open booking in a new window. For questions, call')} <a href="tel:+4791541662">Dan · +47 915 41 662</a>.</p></div></div></section>'''
 content+=f'''<section class="section-small"><div class="wrap practical"><div><h2 class="serif" style="font-size:35px">{t(lang,'Før du bekrefter','Before you confirm')}</h2></div><div>{faq(t(lang,'Pris og avbestilling','Price and cancellation'),t(lang,'Endelig pris og avbestillingsvilkår følger datoene og alternativet du velger i Lodgify. Les oppsummeringen før du bekrefter bestillingen.','The final price and cancellation terms depend on your dates and the option you select in Lodgify. Read the summary before confirming your booking.'))}{faq(t(lang,'Spørsmål om oppholdet?','Questions about your stay?'),t(lang,'Ta gjerne kontakt med Eva eller Dan. Du finner flere detaljer om hytta og praktisk informasjon i gjesteguiden.','Contact Eva or Dan. Our guest guide contains more details about the cabin and practical information.'))}</div></div></section>'''
 layout(lang,'booking',content,t(lang,'Ledige datoer og bestilling','Availability and booking'),t(lang,'Se ledige datoer, pris og vilkår for Brennvik Panorama. Bestill oppholdet gjennom Lodgify.','Check availability, pricing and terms for Brennvik Panorama. Book your stay through Lodgify.'))

def privacy(lang):
 content=head(lang,'privacy',t(lang,'Personvern','Privacy'),t(lang,'Om denne nettsiden og bestillingen din.','About this website and your booking.'))
 content+=f'''<section class="section-small"><div class="wrap legal"><h2>{t(lang,'Nettsiden','This website')}</h2><p>{t(lang,'Nettsiden presenterer Brennvik Panorama, som drives av Skoglund Heim AS. Vi har ikke lagt inn analyseverktøy, markedsføringspiksler eller kontaktskjema på disse sidene. Teknisk logging kan forekomme hos leverandøren som drifter nettsiden.','This website presents Brennvik Panorama, operated by Skoglund Heim AS. We have not added analytics tools, advertising pixels or contact forms to these pages. Technical logging may be performed by the hosting provider.')}</p><h2>{t(lang,'Bestilling via Lodgify','Booking through Lodgify')}</h2><p>{t(lang,'På bestillingssiden lastes innhold fra Lodgify. Opplysninger du gir ved bestilling, og eventuell betaling, behandles gjennom bestillingsløsningen. Se personverninformasjonen og vilkårene som vises der.','The booking page loads content from Lodgify. Details you provide when booking, and any payment, are processed through the booking service. Refer to the privacy information and terms shown there.')}</p><p><a href="https://www.lodgify.com/privacy/" target="_blank" rel="noopener">{t(lang,'Lodgifys personverninformasjon','Lodgify privacy information')} ↗</a></p><h2>{t(lang,'Eksterne lenker','External links')}</h2><p>{t(lang,'Kart, gjesteguide og lenker til lokale opplevelser åpnes hos andre tjenester. Der gjelder tjenestens egne vilkår og personverninformasjon.','Maps, the guest guide and links to local experiences open on other services, where the service’s own terms and privacy information apply.')}</p><h2>{t(lang,'Kontakt','Contact')}</h2><p>{t(lang,'Har du spørsmål om opplysninger knyttet til oppholdet ditt, kontakt Dan på','For questions about information relating to your stay, contact Dan on')} <a href="tel:+4791541662">+47 915 41 662</a>.</p></div></section>'''
 layout(lang,'privacy',content,t(lang,'Personvern','Privacy'),t(lang,'Personverninformasjon for Brennvik Panorama og bestilling gjennom Lodgify.','Privacy information for Brennvik Panorama and booking through Lodgify.'))

for lang in ['no','en']:
 for page in [home,cabin,gallery,explore,location,booking,privacy]: page(lang)
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n')
(OUT/'404.html').write_text('<!doctype html><html lang="nb"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Siden finnes ikke · Brennvik Panorama</title><link rel="stylesheet" href="/site.css"><main class="not-found"><h1>Brennvik Panorama</h1><p>Denne siden finnes ikke. / This page could not be found.</p><a class="button" href="/">Til forsiden / Go to homepage</a></main></html>')
print(f'Generated 14 pages, 404 page and robots.txt; {len(PHOTOS)} gallery photographs.')
